name: Update and Push Domainswild File

on:
  schedule:
    # 每6小執行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手動觸發

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download the latest domainswild.txt
        run: |
          curl -o domainswild.txt https://small.oisd.nl/domainswild

      - name: Replace all *. with . in the file
        run: |
          sed -i 's/\*\./\./g' domainswild.txt

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v5
        with:
          add: 'antiAD-set.txt'
          author_name: pikipig
          author_email: qaqa45194541@example.com
          message: 'Auto-update antiAD-set.txt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
