name: Update and Push Domainswild Files

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: 

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and process domain files
        run: |
          declare -A files=(
            ["antiAD-set-small.txt"]="https://raw.githubusercontent.com/sjhgvr/oisd/main/domainswild_small.txt"
            ["antiAD-set-big.txt"]="https://raw.githubusercontent.com/sjhgvr/oisd/main/domainswild_big.txt"
            ["antiAD-set-nsfw.txt"]="https://raw.githubusercontent.com/sjhgvr/oisd/main/domainswild_nsfw.txt"
          )

          for file in "${!files[@]}"; do
            curl -o "$file" "${files[$file]}"
            sed -i 's/\*\./\./g' "$file"
          done

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v5
        with:
          add: '*.txt'  
          author_name: pikipig
          author_email: qaqa45194541@gmail.com
          message: 'Auto update'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
