name: Replace All Star-Dot Patterns

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run replacement script
        run: |
          FILE_PATH="oisd_small_domainswild.txt"
          sed -i 's/\*\./\./g' "$FILE_PATH"
          echo "Replacement completed!"

      - name: Commit changes
        run: |
          git config --global user.name "your-username"
          git config --global user.email "your-email@example.com"
          git add "$FILE_PATH"
          git commit -m "Auto-replace *. with ."
          git push
